name: AI-toxique Bot Runner

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/10 * * * *'  # toutes les 10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          npm install

      - name: Run AI-toxique bot
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          OWNER_NUMBER: '+22395064497'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STICKER_URLS: 'https://carder.top/imagens/1751137690247-769501706.jpg,https://carder.top/imagens/1751137688214-14179631.jpg,https://carder.top/imagens/1751137686088-89302512.jpg,https://carder.top/imagens/1751137691992-182332617.jpg,https://carder.top/imagens/1751137693867-451938375.jpg,https://carder.top/imagens/1751137696223-566573331.jpg'
          BOT_PREFIX: '!'
        run: npm start
